language: java
sudo: false
dist: trusty
script:
  - jdk_switcher use oraclejdk8
script: mvn clean verify
script: mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
env:
  global:
    - secure: "pmNBqCAW1rc4WKHEmnroZNwAMus18K1VWhRYwt+CN0acH8griJp612tjwWcI\n9XkZcSPR0CJx1TZqGDZZTFH44Pkm6ELU1kc54xtJR6WMXnubEVoEom0tcv/1\nNyzxv9UFJfaNgaTESww+OXSlO9wQre5ZS0/wn2xrz0+twtOPYDU="
    - secure: "CZ9mejMLJdrh+a5TFXsNSiYyK9K/zNYOtubv2sPq1OEGhuohdUfLtdsk7bK9\nQcIlhZjrE5Q/wVgjZcFsnVpKhnUSRLC7sTOh6tu08EwpNtnNLl5AeUztOMCs\nxhG5H7jDu9uEH81WDZnIuK4Zq4qxXx523rnqQfk4DsTCKLVh9jI="

addons:
  apt:
    packages:
      - python-yaml

before_install:
  - git submodule update --init --recursive

after_success:
  - mvn clean test jacoco:report coveralls:report

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6d8b14c5b83c43490417
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always